/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.tapifolti.resttest.api;

public class WebTest {
  public static void addV(DoubleVector v1, DoubleVector v2, DoubleVector vRes) {
    WebTestJNI.addV(DoubleVector.getCPtr(v1), v1, DoubleVector.getCPtr(v2), v2, DoubleVector.getCPtr(vRes), vRes);
  }

  public static void mulV(DoubleVector v1, DoubleVector v2, DoubleVector vRes) {
    WebTestJNI.mulV(DoubleVector.getCPtr(v1), v1, DoubleVector.getCPtr(v2), v2, DoubleVector.getCPtr(vRes), vRes);
  }

  public static void expV(DoubleVector v1, DoubleVector vRes) {
    WebTestJNI.expV(DoubleVector.getCPtr(v1), v1, DoubleVector.getCPtr(vRes), vRes);
  }

}
